[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/random-color-generator/"

[watch]
watch = ["./index.html", "src/", "style/", "static/"]

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
# run tailwind build with webpack
command_arguments = [
    "-c",
    "[ ! -d \"./node_modules\" ] && npm i || :; npm run build_css",
]
